import type { Achievement } from '@/types';

/** 16 achievements — verbatim from Pro. */
export const ACHIEVEMENTS: readonly Achievement[] = [
  {
    id: 'first_session',
    name: 'Primer Pas',
    desc: 'Completa la primera sessió de focus',
    ico: '🌱',
    check: (s) => s.todaySess >= 1,
  },
  {
    id: 'streak_3',
    name: 'Constant',
    desc: 'Aconsegueix una ratxa de 3 dies',
    ico: '🔥',
    check: (s) => s.streak >= 3,
  },
  {
    id: 'streak_7',
    name: 'Imparable',
    desc: 'Ratxa de 7 dies seguits',
    ico: '⚡',
    check: (s) => s.streak >= 7,
  },
  {
    id: 'streak_30',
    name: 'Llegenda',
    desc: 'Ratxa de 30 dies!',
    ico: '👑',
    check: (s) => s.streak >= 30,
  },
  {
    id: 'cards_50',
    name: 'Explorador',
    desc: 'Revisa 50 flashcards',
    ico: '📇',
    check: (s) => s.quizTotal >= 50,
  },
  {
    id: 'cards_500',
    name: 'Erudit',
    desc: 'Revisa 500 flashcards',
    ico: '🧠',
    check: (s) => s.quizTotal >= 500,
  },
  {
    id: 'mem_80',
    name: "Memòria d'Acer",
    desc: 'Arriba al 80% de força de memòria',
    ico: '💎',
    check: (s) => s.memStrength >= 80,
  },
  {
    id: 'hours_10',
    name: 'Dedicat',
    desc: "Acumula 10 hores d'estudi",
    ico: '⏰',
    check: (s) => s.totalMin >= 600,
  },
  {
    id: 'hours_50',
    name: 'Mestre',
    desc: "Acumula 50 hores d'estudi",
    ico: '🏆',
    check: (s) => s.totalMin >= 3000,
  },
  {
    id: 'hours_100',
    name: "Acadèmic d'Elit",
    desc: "100 hores d'estudi total",
    ico: '🎓',
    check: (s) => s.totalMin >= 6000,
  },
  {
    id: 'exam_10',
    name: 'Estudiant Model',
    desc: 'Completa 3 exàmens',
    ico: '📝',
    check: (s) => s.quizzes && s.quizzes.length >= 3,
  },
  {
    id: 'level_10',
    name: 'Veterà',
    desc: 'Arriba al nivell 10',
    ico: '⭐',
    check: (s) => s.level >= 10,
  },
  {
    id: 'level_25',
    name: 'Expert',
    desc: 'Arriba al nivell 25',
    ico: '💫',
    check: (s) => s.level >= 25,
  },
  {
    id: 'level_50',
    name: 'Gran Mestre',
    desc: 'Arriba al nivell 50',
    ico: '🌟',
    check: (s) => s.level >= 50,
  },
  {
    id: 'deep_work',
    name: 'Deep Worker',
    desc: 'Completa una sessió de 90+ min',
    ico: '🔮',
    check: (s) => s.pomCount > 0,
  },
  {
    id: 'pom_10',
    name: 'Pomodoro Master',
    desc: 'Completa 10 pomodoros',
    ico: '🍅',
    check: (s) => s.pomCount >= 10,
  },
];
