/**
 * 32 technical-jargon patterns used by the Feynman tutor to detect
 * "competence illusion" — verbatim from Pro.
 */
export const JARGON_PATTERNS: readonly string[] = [
  'paradigma',
  'axiomàtic',
  'epistemològic',
  'ontològic',
  'heurístic',
  'sinàptic',
  'neurocognitiu',
  'metacogni',
  'algorítmic',
  'exponencial',
  'logarítmic',
  'derivada parcial',
  'integral definida',
  'isomorfisme',
  'homeomorfisme',
  'estequiometria',
  'termodinàmic',
  'entropia',
  'catalitzador',
  'polímers',
  'electròfil',
  'nucleòfil',
  'cinètic',
  'estocàstic',
  'asimptòtic',
  'convergent',
  'divergent',
  'vectorial',
  'escalar',
  'tensorial',
  'ortogonal',
  'hermitià',
  'hamiltonià',
];
