import type { Friend } from '@/types';

export const MOCK_FRIENDS: Friend[] = [
  {
    id: 'f1',
    name: 'Martí',
    avatar: '👨‍🎓',
    level: 25,
    totalXp: 12500,
    streak: 45,
    weeklyMinutes: 650,
    isOnline: true,
  },
  {
    id: 'f2',
    name: 'Laia',
    avatar: '👩‍💻',
    level: 22,
    totalXp: 9800,
    streak: 12,
    weeklyMinutes: 420,
    isOnline: false,
  },
  {
    id: 'f3',
    name: 'Pol',
    avatar: '🧑‍🔬',
    level: 18,
    totalXp: 6200,
    streak: 30,
    weeklyMinutes: 380,
    isOnline: true,
  },
  {
    id: 'f4',
    name: 'Clàudia',
    avatar: '👩‍🏫',
    level: 15,
    totalXp: 4500,
    streak: 5,
    weeklyMinutes: 210,
    isOnline: false,
  },
  {
    id: 'f5',
    name: 'Marc',
    avatar: '👨‍🚀',
    level: 12,
    totalXp: 3100,
    streak: 2,
    weeklyMinutes: 150,
    isOnline: true,
  },
  {
    id: 'f6',
    name: 'Anna',
    avatar: '👩‍🎨',
    level: 8,
    totalXp: 1800,
    streak: 8,
    weeklyMinutes: 90,
    isOnline: false,
  },
  {
    id: 'f7',
    name: 'Jordi',
    avatar: '👨‍🔧',
    level: 5,
    totalXp: 950,
    streak: 1,
    weeklyMinutes: 45,
    isOnline: true,
  },
];
