/**
 * PWA utilities: service worker registration, install prompt, and connectivity.
 *
 * `initPWA()` should be called once at app boot (main.tsx).
 */

// ── Install prompt ──────────────────────────────────────────────────────────

let deferredPrompt: BeforeInstallPromptEvent | null = null;
const listeners = new Set<() => void>();

interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>;
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }>;
}

export function getInstallPrompt(): BeforeInstallPromptEvent | null {
  return deferredPrompt;
}

export function onInstallPromptChange(cb: () => void): () => void {
  listeners.add(cb);
  return () => listeners.delete(cb);
}

export async function triggerInstall(): Promise<boolean> {
  if (!deferredPrompt) return false;
  deferredPrompt.prompt();
  const { outcome } = await deferredPrompt.userChoice;
  deferredPrompt = null;
  listeners.forEach((cb) => cb());
  return outcome === 'accepted';
}

/**
 * Detect iOS Safari (no beforeinstallprompt, needs manual Add to Home Screen).
 */
export function isIOSSafari(): boolean {
  const ua = navigator.userAgent;
  const isIOS = /iPad|iPhone|iPod/.test(ua) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);
  const isSafari = /Safari/.test(ua) && !/CriOS|FxiOS|OPiOS|EdgiOS/.test(ua);
  return isIOS && isSafari;
}

// ── Online / Offline ────────────────────────────────────────────────────────

let _online = typeof navigator !== 'undefined' ? navigator.onLine : true;
const onlineListeners = new Set<(online: boolean) => void>();

export function isOnline(): boolean {
  return _online;
}

export function onConnectivityChange(cb: (online: boolean) => void): () => void {
  onlineListeners.add(cb);
  return () => onlineListeners.delete(cb);
}

// ── Init ────────────────────────────────────────────────────────────────────

export function initPWA(): void {
  // Install prompt
  window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault();
    deferredPrompt = e as BeforeInstallPromptEvent;
    listeners.forEach((cb) => cb());
  });

  // Connectivity
  window.addEventListener('online', () => {
    _online = true;
    onlineListeners.forEach((cb) => cb(true));
  });
  window.addEventListener('offline', () => {
    _online = false;
    onlineListeners.forEach((cb) => cb(false));
  });

  // Register service worker (generated by vite-plugin-pwa)
  if ('serviceWorker' in navigator) {
    import('virtual:pwa-register').then(({ registerSW }) => {
      registerSW({ immediate: true });
    }).catch(() => {
      // SW registration failed (dev mode without build, etc.) — non-critical.
    });
  }
}
